### ISSUE TITLE
Mac GUI daemon start failed

### ISSUE THREAD

**Issue by sumitnagariya** [loki-project/loki-gui#13]
Unable to start daemon on mac.

ERROR	msgwriter	src/common/scoped_message_writer.h:102	Error: Couldn't connect to daemon: 127.0.0.1:22023

INFO 	logging	contrib/epee/src/mlog.cpp:185	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO,logging:INFO,msgwriter:INFO

**Comment by Doy-lee** [comment]
Please try the builds available in issue #12
