### ISSUE TITLE
Daemon failed to start

### ISSUE THREAD

**Issue by peteshand** [loki-project/loki-gui#17]
I get the following error when trying to connect to the network.
"Please check your wallet and daemon log for errors. You can also try start lokid.exe manually."
First question, where are the logs? this should be clearly stated in the error.
Also where is lokid.exe? it isn't located in the same folder as loki-wallet-gui.exe

**Comment by Doy-lee** [comment]
Logs are generated in the same directory as the executable, loki-wallet-gui.log.

Currently Windows Defender (and possibly other anti virus software) flag lokid.exe as it contains mining software. If you view the zip, you will see lokid.exe is present. You should check your AV software for any quarantining that has occurred and add an exception for the executable or the directory.

**Comment by peteshand** [comment]
In that case it's most likely lokid.exe had been removed by Windows Defender. I downloaded the latest release and run it between Windows Defender had a chance to remove it and it worked.
