### ISSUE TITLE
lokid Mac fails to start

### ISSUE THREAD

**Issue by peteshand** [loki-project/loki-gui#18]
OSX 10.10.2

When manually starting lokid on Mac i get the following error

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/loki-wallet-gui.app/Contents/MacOS/lokid (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/loki-wallet-gui.app/Contents/MacOS/lokid (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
logout

**Comment by Doy-lee** [comment]
Please try the build in #12
