### ISSUE TITLE
Loki mac gui 0.1.0 crashing upon launch

### ISSUE THREAD

**Issue by eyegithub** [loki-project/loki-gui#20]
Hi, i downloaded the latest version, but after unzipping and putting the "loki-wallet-gui" in the apps folder and double clicking it, it immediately crashes without even opening. Anything i missed ?
I'm on high sierra 10.13.4.

**Comment by Doy-lee** [comment]
Hi, can you try launching the gui through the terminal and pasting any console output you receive.

**Comment by eyegithub** [comment]
ok, as i'm a terminal noob, can you tell me how to do this ?

**Comment by Doy-lee** [comment]
Open a terminal in the folder you downloaded the zip from and extracted the folder. Then right click on the app and click on show contents.

From there I believe it's in loki-wallet-gui.app/Contents/MacOS/loki-wallet-gui. You will want to open the terminal in this folder, and then use the command "./loki-wallet-gui" in the terminal to launch the GUI.

**Comment by eyegithub** [comment]
hmm, not sure it's possible in Mac Os to open a terminal window in a specific finder window that's open...

Ok, I tried these things :

1 I fired up terminal, drag & dropped the original loki-wallet-gui folder in terminal, I hit enter and I'm getting : -bash: /Applications/loki-wallet-gui.app: is a directory ; when I paste your command I get : -bash: ./loki-wallet-gui: No such file or directory

2 same as 1 but I don't hit enter and paste your command, then hit enter, I'm getting : -bash: /Applications/loki-wallet-gui.app: is a directory

3 terminal, drag & dropped the loki-wallet-gui from the show contents without hitting enter, then pasted your command, but I'm getting "Illegal instruction: 4" and loki quits.

**Comment by Doy-lee** [comment]
I'll have to investigate this further. The binaries are built against OSX 10.10.5 which I assumed newer OSX's wouldn't have trouble with. There's a bit of documentation on why this is happening and I'll be having a look at seeing if I can produce some builds that work.

In the meantime building from source or just sticking with CLI is currently the only option.

**Comment by Doy-lee** [comment]
Hi, I have created some new binaries that may fix this issue. Please try the following,

https://loki.network/wp-content/uploads/2018/05/loki-wallet-gui-mac64-v0.1.0.zip

Thanks.

**Comment by monamifoto** [comment]
Gui works for me! thanks

**Comment by Doy-lee** [comment]
I've had some feedback that this new build is being received well and have updated links in the release page. Feel free to re-open if there's any more issues.

**Comment by cculianu** [comment]
Hi @Doy-lee ,

Thanks for responding.  I did some research and figured out that brew was building OpenSSL 1.0.2q from source on my VM with El Capitan on it.  As such, I think OpenSSL was doing some fancy CPU detection (or maybe the compiler had extended instructions turned on) -- and I think that's what caused it to not work on older CPUs that lacked newer instructions.  At least that's the theory.

OpenSSl 1.0.2p was bottled (pre built) and that's why it worked for me, whereas 1.0.2q would get compiled.. with the offending not-100%-backward-compatible-instructions turned on.

That's my theory at least.

Thanks a lot for responding though. 👍
