### ISSUE TITLE
Loki Mac GUI - Local Node - Daemon failed - Version 14.0

### ISSUE THREAD

**Issue by Vinos25** [loki-project/loki-gui#23]
Hi,
When I first synced my Loki Wallet it worked fine and I was able to get my token transferred in as well. Post that its been 2 weeks that I didnt login and tried logging in today - I am able to login fine but not able to run the daemon with local node (I was able to when I did it the first time). I tried remote node and it worked but my balance shows '0'.
The history doesnt show any transaction as well.
I have checked its the same wallet with same seed and view/spend addresses.
Please help - I am not very technically savvy.

Thanks!

**Comment by Doy-lee** [comment]
Hi, in the GUI in Settings and scrolling down to Debug Info, there's the "Wallet Creation Height" setting which you can click to change. Try re-setting this to 0 and let it scan the block chain again to re-evaluate your balance. This can be used on both remote/local nodes.

You may also run the daemon manually in its own terminal and let the GUI sync to it. There could be a myriad of issues preventing the daemon from running-, mostly user error, so going manually will let you see the output in the console and continue from there.
