### ISSUE TITLE
Not available for 32 bit windows

### ISSUE THREAD

**Issue by jayanthmankavil** [loki-project/loki-gui#25]

**Comment by Doy-lee** [comment]
Hi, please see the readme in the Windows section 

> The Loki GUI on Windows is 64 bits only; 32-bit Windows GUI builds are not officially supported anymore.

At the time of Loki's fork up to release, Monero deprecated the 32bit build for Windows which we have inherited by default from matching their repository. As such we don't have 32 bit executables, in the mean time we are working on alternatives such as web and mobile wallets and may revisit this in the future.

Going forward though, 32 bit will not be at the top of our priorities.
