### ISSUE TITLE
GUI Crash on OSX

### ISSUE THREAD

**Issue by jorritjaap** [loki-project/loki-gui#26]
Hi my Wallet crashed on OSX. Please find attached error log. Hope this helps.

[loki error.txt](https://github.com/loki-project/loki-gui/files/2122576/loki.error.txt)

**Comment by Doy-lee** [comment]
Are you running a full node or a remote node? If you're on a full node, does this occur if you run on a remote node? You'd start up the GUI without starting the daemon and setting a remote node in settings.

If it works, it suggests that the blockchain data might be corrupted and it'd be recommended to re-sync. The gui is currently crashing on doRefresh() which is when it queries the daemon.

**Comment by Doy-lee** [comment]
Closed because of no further leads and issue age.
