### ISSUE TITLE
i can not run the wallet

### ISSUE THREAD

**Issue by hadinet29** [loki-project/loki-gui#28]
hello
i have difficulty in running wallet i read the instruction but was not useful
when i click on  start-low-graphics-mode.bat  and run it as admin>>>nothing happen

i have windows10   64bit 

thank you

**Comment by Doy-lee** [comment]
Hi, please double check any anti-virus programs you may have running that could prematurely terminate the program.

My recommendation is to collect some logs. There are log files generated in the same directory as the executable. Further more launching the GUI with DebugView (https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) open will also collect some logs emitted by QT which is worth looking at.

**Comment by hadinet29** [comment]
I make recovery to my pc and then every thing is fine

thank you
