### ISSUE TITLE
i have issue with back up my wallet

### ISSUE THREAD

**Issue by hadinet29** [loki-project/loki-gui#29]
hello
I  did try to back up my wallet in new pc by sead ,,, then after back up I get zero balance and I surprised that receiving address is different!!!! 
while when I open old wallet in old pc every thing is fine

I have windows

thank you

**Comment by Doy-lee** [comment]
Please recheck your seed and ensure the daemon is completely synced on your new PC by remote node or syncing locally. Seeds reproduce the same wallet file every time.

**Comment by Doy-lee** [comment]
Closed because of no further leads and issue age.
