### ISSUE TITLE
Wallet does not work win 10 64

### ISSUE THREAD

**Issue by youriyzp** [loki-project/loki-gui#30]
1.Add 'loki-gui-win...'  folder to exclusions in Windows Defender
2. Run lokid,synchronized
3. run loki-wallet-gui: does not work
4 run start-low-graphics-mode -closed itself in 2 seconds
What should I do to make this work?
after run loki-wallet-gui debugwiew:
00000001	0.00000000	[7144] Type of item #0 of subgroup #0: image	
00000002	0.00007287	[7144] Type of item #0 of subgroup #1: image	
00000003	0.85010147	[7144] Suspending

**Comment by Doy-lee** [comment]
Unfortunately the information from debug view hasn't told us anything that could help us debug. There is also the log loki-gui-wallet log file in the same directory which may have more information that could be useful to determine why it's crashing.

May I also know the specs of the machine? Low graphics mode moves over to software rendering which almost always should work in the worst case. I'd also be wary of any other anti-virus software you may have running on the machine that could be terminating the process shortly after launch.

**Comment by youriyzp** [comment]
i78700k,16Gb,1080ti*4
I do not see the log file in the Loki directory
where is he?

**Comment by youriyzp** [comment]
[loki-wallet-gui.exe.15648.dmp.7z.zip](https://github.com/loki-project/loki-gui/files/2169356/loki-wallet-gui.exe.15648.dmp.7z.zip)

**Comment by Doy-lee** [comment]
Looks like an unhandled exception was triggered. To isolate the problem, one suggestion could be to try and launch the GUI in Windows under Safe Mode.

**Comment by Doy-lee** [comment]
Closed because of no further leads and issue age.
