### ISSUE TITLE
Daemon has synced but Wallet will not Remote or Local Node

### ISSUE THREAD

**Issue by TheRebelOfBabylon** [loki-project/loki-gui#31]
I'm running Loki Gui Wallet on Windows 10, 64 bit. It's a new computer so it may have something to do with Defender or Firewall settings but as the title mentions, my daemon has downloaded the full blockchain and has synced but my wallet won't sync or display my balance.

**Comment by Doy-lee** [comment]
For clarification, when you mention that the wallet won't sync, is this the GUI's Network Status being stuck at "Synchronizing" whilst the daemon is synced with the network?

My suggestion is to check that in the settings of the GUI the Wallet Creation Height has been set to an appropriate block height from when you started receiving transactions to your wallet. The safest option would be to set this to 0 and letting it scan the entire chain for transactions that belong to you.

**Comment by TheRebelOfBabylon** [comment]
Yes to your clarification. I changed the wallet creation height to 0 and the issue persists.

**Comment by Doy-lee** [comment]
Please launch the daemon separately in the terminal with the command lokid --log-level 1 and upload the output. Looks like the daemon is having problems communicating to the wallet, so we'll be able to see whats happening with this.

Sometimes the wallet mis-reports that it is synced whilst the daemon is still syncing. Currently block height can be verified through any block explorer like lokiblocks.com

**Comment by TheRebelOfBabylon** [comment]
![lokid_boot](https://user-images.githubusercontent.com/33608940/42853615-8595073c-8a05-11e8-98c9-8c06a49b2d2f.PNG)

So this is the output when I simply run lokid as admin. I type in the command "lokid --log-level 1" and I get three lines of output before lokid crashes.

**Comment by TheRebelOfBabylon** [comment]
Hello, I updated my loki gui wallet to 0.2.0 and the issue was resolved!! I see my balance now. Thank you very much for the help.
