### ISSUE TITLE
Unix missing loki-wallet-gui file

### ISSUE THREAD

**Issue by chaos-ruins** [loki-project/loki-gui#34]
The latest version loki-gui-unix64-v0.1.1 is missing the file loki-wallet-gui as I get the error start-gui.sh: 7: start-gui.sh: ./loki-wallet-gui: not found.

**Comment by Doy-lee** [comment]
I should of been more skeptical that the final zip size was suspiciously small. rm -rf with tab completion to delete the log file ... release has been updated thanks.

**Comment by chaos-ruins** [comment]
Thank you for fixing it.
