### ISSUE TITLE
Payment sent to Unknown Address(address has changed unexpected..)

### ISSUE THREAD

**Issue by DrOctavius** [loki-project/loki-gui#48]
Hi,
Recently i have sent some LOKI to a specific COPIED address (deposit address).
The address was verified by me everywhere where i have pasted...
Now my question...is it possible for GUI Loki to change somehow the address after i confirm everything?!
Because as i understand now i've lost them...
Can i restore them somehow?! Or can i create the Wallet address where they have being sent?!

THank you,... (i don't understand from where these address has appeared...i though i have taken from somewhere..but haven't found nowhere where it might be...)

**Comment by jagerman** [comment]
I see you closed this, so hopefully it was resolved successfully.  Just a comment in case someone else stumbles across this: this was most likely sending to an integrated address, which is really a unique address formed from a regular address and a payment ID, but when you look it up in the transfers list you'll see the (completely different) regular address, not the integrated address, listed as the recipient.

**Comment by DrOctavius** [comment]
Hi @jagerman , well i haven't resolved it..i though my issue wasn't relevant for posting here, this is why i closed it, but thank you for responding... because still...the LOKI dindn't arrive to the Destination Address that was generated by the LOKI-GUI...
The deposit address i took from tradeorge.com
LK8CGQ17G9R3ys3Xf33wCeViD2B95jgdpjAhcRsjuheJ784dumXn7g3RPAzedWpFq364jJKYL9dkQ8mY66sZG9BiCw7bF8iFng7FdRQ9Ka
It's too long than the standard one...(so yes, maybe integrated address, i'm not sure..)
But when i made the transaction it sent to: 
L9RXFbBcesu3ys3Xf33wCeViD2B95jgdpjAhcRsjuheJ784dumXn7g3RPAzedWpFq364jJKYL9dkQ8mY66sZG9Bi94F2oPS
It's shorter and different from the one i Paste it..
Should i write to Tradeogre? Or can i decode the Copied address from tradeogre and see if it's equal to the one that has being sent?

Thank you again!

**Comment by DrOctavius** [comment]
Or may it be tradeogre.com a SCAM system?

**Comment by jagerman** [comment]
> LK8CGQ...

> L9RXFb...

This is normal: the second one is the actual trade ogre wallet, the first one is what's called an integrated address that encodes both the wallet (the L9RX...) and a unique payment ID into a specially encoded address (it's longer and has a different prefix than a regular loki address).  My TradeOgre deposit address, for example, is:

LK8CGQ17G9R3ys3Xf33wCeViD2B95jgdpjAhcRsjuheJ784dumXn7g3RPAzedWpFq364jJKYL9dkQ8mY66sZG9BiC..... (where the "....." is 17 letters are different than yours--that's the unique payment ID for my loki account on trade ogre).  I just sent a 1 LOKI deposit and it shows up in my wallet transfer log as going to:

L9RXFbBcesu3ys3Xf33wCeViD2B95jgdpjAhcRsjuheJ784dumXn7g3RPAzedWpFq364jJKYL9dkQ8mY66sZG9Bi94F2oPS

that is, *exactly* the same as yours.  That *is* the correct TradeOgre wallet.  As for your missing deposit, if it still isn't showing up on TradeOgre (even under Deposit History) you'll need to get in touch with them along with your transaction id.  (My 1 LOKI deposit showed up within a minute -- currently at 2/20 confirmations).

**Comment by DrOctavius** [comment]
@jagerman THank you again, i wrote them to tradeogresupport@protonmail.com but i'm not sure if thats their support email... i hope is it.. i'm a little bit calmer now :) Yes i also waited for confirmations, and everything went through!

**Comment by KeeJef** [comment]
Check your wallet version, you may be on different blockchain to the current mainchain. The current version of the GUI wallet is 1.0.0 and the current block height is 110290 if these don't match please upgrade your GUI wallet and resend your TX

**Comment by DrOctavius** [comment]
@KeeJef Hey, well i'm using 2.0.0 => i should reverse back!?

**Comment by DrOctavius** [comment]
![image](https://user-images.githubusercontent.com/32667431/46392714-faf7f080-c6ea-11e8-9ade-360808fe4f51.png)

**Comment by KeeJef** [comment]
I assume you are using 0.2.0, there is no version of the wallet with version number 2.0.0 in which case i would recommend updating to version 1.0.0 which is in the "Getting started" section on our website. If you are still having issues i recommend you use a remote node to sync the blockchain

**Comment by DrOctavius** [comment]
Sorry, yes i've checked again... yes i downloaded again.. the latest is 1.0.3

**Comment by KeeJef** [comment]
That is the latest version of the CLI wallet, you will want to use the GUI wallet, latest version can be downloaded here https://github.com/loki-project/loki-gui/releases/tag/v1.0.0

**Comment by DrOctavius** [comment]
Thank you @KeeJef !

**Comment by DrOctavius** [comment]
I'll recheck again, and write my results!

**Comment by DrOctavius** [comment]
![image](https://user-images.githubusercontent.com/32667431/46393255-12d07400-c6ed-11e8-8a9d-2822a4fcdc66.png)
Yes, my funds are still there :), so i'll retry everything!

**Comment by DrOctavius** [comment]
![image](https://user-images.githubusercontent.com/32667431/46394263-41e8e480-c6f1-11e8-8a99-e9f3016f4251.png)
Yes everything works fine! Thank you everyone for your support!
