### ISSUE TITLE
build error win10 64 bit

### ISSUE THREAD

**Issue by blockchainbuzz** [loki-project/loki-gui#5]
Hi I am having trouble build the gui from the source, any idea how to solve it?
`[100%] Built target unbound
Install the project...
-- Install configuration: "Release"
-- Installing: C:/loki/loki-gui/loki/lib/libunbound.a
/c/loki/loki-gui/loki/build/release /c/loki/loki-gui /c/loki/loki-gui
/c/loki/loki-gui /c/loki/loki-gui
make: Entering directory '/c/loki/loki-gui/src/zxcvbn-c'
g++ -I. -std=c++11 -O2 -Wall -Wextra \
        -o dictgen dict-generate.cpp
dict-generate.cpp: In function 'void CreateArrays(NodeSPtr, StringIntSet_t&, StringOfInts&, Uint64Vect&, UintVect&)':
dict-generate.cpp:887:43: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'std::__cxx11::basic_string<int>::size_type {aka long long unsigned int}' [-Wformat=]
         snprintf(Tmp, sizeof Tmp, "%lu", x);
                                           ^
./dictgen -o dict-src.h words-eng_wiki.txt words-female.txt words-male.txt words-passwd.txt words-surname.txt words-tv_film.txt
cc -I. -O2 -Wall -Wextra -Wdeclaration-after-statement -c -o zxcvbn-inline.o zxcvbn.c
ar cvq libzxcvbn.a zxcvbn-inline.o
a - zxcvbn-inline.o
cc -I. -O2 -Wall -Wextra -Wdeclaration-after-statement -o test-statlib test.c libzxcvbn.a  -lm
make: Leaving directory '/c/loki/loki-gui/src/zxcvbn-c'
You are currently on commit add582a
The most recent tag was at add582a
You are building a tagged release
fatal: No annotated tags can describe 'add582a90e7e679e00cff365a4c99f111f2d2fb0'.
However, there were unannotated tags: try --tags.
/c/loki/loki-gui/loki /c/loki/loki-gui /c/loki/loki-gui
You are currently on commit 517abb24
The most recent tag was at 1265676e
You are ahead of or behind a tagged release
fatal: No annotated tags can describe '517abb24c2f7c49a8d77c63ddc074ebcd00714ba'.
However, there were unannotated tags: try --tags.
/c/loki/loki-gui /c/loki/loki-gui
Info: creating stash file C:\loki\loki-gui\build\.qmake.stash
Warning: dropping duplicate messages in 'C:/loki/loki-gui/build/translations/loki-core_ar.qm':

* Context: WizardPassword
* Source:  <br>Note: this password cannot be recovered. If you forget it then the wallet will have to be restored from its 25 word mnemonic seed.<br/><br/>
                        <b>Enter a strong password</b> (using letters, numbers, and/or symbols):

Updating 'C:/loki/loki-gui/build/translations/loki-core_ar.qm'...
Removing translations equal to source text in 'C:/loki/loki-gui/build/translations/loki-core_ar.qm'...
    Generated 204 translation(s) (204 finished and 0 unfinished)
    Ignored 263 untranslated source text(s)
Warning: dropping duplicate messages in 'C:/loki/loki-gui/build/translations/loki-core_cat.qm':

* Context: WizardPassword
* Source:  <br>Note: this password cannot be recovered. If you forget it then the wallet will have to be restored from its 25 word mnemonic seed.<br/><br/>
                        <b>Enter a strong password</b> (using letters, numbers, and/or symbols):
`

**Comment by Doy-lee** [comment]
Hi, there's nothing in the posted snippet that suggests a broken build?
