### ISSUE TITLE
Linux Mint 18.3 Cinnamon 64-bit

### ISSUE THREAD

**Issue by jazzjazzy** [loki-project/loki-gui#7]
Trying to run the start-gui.sh I get this error 

~/loki-gui-linux64-v0.1.0 $ ./start-gui.sh 
**./loki-wallet-gui: error while loading shared libraries: VBoxOGLcrutil.so: cannot open shared object file: No such file or directory**

VBoxOGLcrutil.so seem to be a VirtualBox lib, is there anyway around this?

**Comment by Lucifer1903** [comment]
I also got this error on both Fedora-24 and Debian-8. Please fix it.

**Comment by Doy-lee** [comment]
Hey, please try this build of the gui that has been built natively. If the results are positive, I'll be updating the release links to this new build.

https://loki.network/wp-content/uploads/2018/05/loki-gui-linux64-v0.1.0-build-native.zip
SHA256: a813c3d2729ce17faaf428c1342ceac36555b994cbb49b7f0bb47511911a5001

**Comment by Lucifer1903** [comment]
That works thanks

**Comment by jazzjazzy** [comment]
Worked

**Comment by Doy-lee** [comment]
That's great to hear.
