### ISSUE TITLE
MacOS GUI wallet 2.0.2 does not have execution permission, Mojave 10.14

### ISSUE THREAD

**Issue by lilotter45** [loki-project/loki-gui#78]
Just updated the MacOS GUI wallet from 1.x to 2.0.2, on OS X Mojave 10.14, and received the error "The application 'loki-wallet-gui' can't be opened."

I was able to resolve this by using chmod to make the file executable, but in searching for a resolution I did find that others are getting the same error.

**Comment by msgmaxim** [comment]
This appears to be the same issue as reported in https://github.com/loki-project/loki/issues/384. I have just updated the 2.0.2 binary, which should address this. Would you be able to download the new binary and confirm that?

**Comment by lilotter45** [comment]
I did download the new binary and the issue appears to be resolved.

The issue you referenced does appear to be the same. Sorry about that, I didn't check that project before posting here.
